// SPDX-License-Identifier: Apache-2.0
// Copyright Contributors to the ACES Project.
// Mechanically adapted from aces-core 069b0bc3e1f6c62820f19fdae2fecec3f4fc0f80.
// Generated by Tools/ACES2~/port-ctl.cjs. Doubles keep the reference precision.
using System;
using static System.Math;
using Unity.Collections;
using Unity.Mathematics;
namespace CustomToneMapping.Baker.ACES2
{
// Types: CTL float[3] is double3, float[2] is double2, and float[3][3] is double3x3 with CTL row i stored in
// column i, so m[i][j] reads the same as in the CTL. Larger tables are NativeArray (Allocator.Temp). Nothing
// allocates managed memory, so the whole file compiles under Burst, which supports System.Math on doubles.
internal static class AcademyTransform
{
    internal struct Chromaticities
    {
        internal double2 red, green, blue, white;
    }
    // The limiting displays the package bakes for, all D65.
    internal static readonly Chromaticities Rec709Primaries = new Chromaticities {red=new double2(.64, .33), green=new double2(.30, .60), blue=new double2(.15, .06), white=new double2(.3127, .3290)};
    internal static readonly Chromaticities Rec2020Primaries = new Chromaticities {red=new double2(.708, .292), green=new double2(.170, .797), blue=new double2(.131, .046), white=new double2(.3127, .3290)};
    static NativeArray<T> Copy<T>(NativeArray<T> v) where T : struct
    {
        var r = new NativeArray<T>(v.Length, Allocator.Temp, NativeArrayOptions.UninitializedMemory);
        r.CopyFrom(v);
        return r;
    }
    static double3 With(double3 v, int i, double x) { v[i] = x; return v; }
    const double PI = Math.PI;
    const double M_PI = Math.PI;
    const double HALF_POS_INF = double.PositiveInfinity;
    const double HALF_NEG_INF = double.NegativeInfinity;
    static double pow(double a, double b) => Pow(a,b);
    static double pow10(double a) => Pow(10,a);
    static double sqrt(double a) => Sqrt(a);
    static double log(double a) => Log(a);
    static double log10(double a) => Log10(a);
    static double exp(double a) => Exp(a);
    static double fabs(double a) => Abs(a);
    static double floor(double a) => Floor(a);
    static double cos(double a) => Cos(a);
    static double sin(double a) => Sin(a);
    static double atan2(double a, double b) => Atan2(a,b);
    static double fmod(double a, double b) => a%b;
    static int min(int a, int b) => Math.Min(a,b);
    static int max(int a, int b) => Math.Max(a,b);
    static double3 mult_f_f3(double s, double3 v) => s*v;
    // Row vector times matrix; with CTL rows stored as columns that is math.mul(m, v).
    static double3 mult_f3_f33(double3 v, double3x3 m) => math.mul(m, v);
    // CTL a*b with rows stored as columns is math.mul(b, a).
    static double3x3 mult_f33_f33(double3x3 a, double3x3 b) => math.mul(b, a);
    static double3x3 mult_f_f33(double s, double3x3 m) => s*m;
    static double3x3 invert_f33(double3x3 m) => math.inverse(m);
    internal static double min(double a,
        double b)
    {
        if (a < b)
            return a;
        else
            return b;
    }

    internal static double max(double a,
        double b)
    {
        if (a > b)
            return a;
        else
            return b;
    }

    internal static double clamp(double @in,
        double clampMin,
        double clampMax)
    {
        return max(clampMin, min(@in, clampMax));
    }

    internal static double3 clamp_f3(double3 @in,
        double clampMin,
        double clampMax)
    {
        double3 @out = default;
        @out[0] = clamp(@in[0], clampMin, clampMax);
        @out[1] = clamp(@in[1], clampMin, clampMax);
        @out[2] = clamp(@in[2], clampMin, clampMax);

        return @out;
    }

    internal static double3 f3_from_f(double a)
    {
        double3 f3 = new double3(a, a, a);
        return f3;
    }

    internal static double round(double x)
    {
        int x1 = default;

        if (x < 0.0)
            x1 = (int)(x - 0.5);
        else
            x1 = (int)(x + 0.5);

        return x1;
    }

    internal static int sign(double x)
    {
        int y = default;
        if (x < 0)
        {
            y = -1;
        }
        else if (x > 0)
        {
            y = 1;
        }
        else
        {
            y = 0;
        }

        return y;
    }

    internal static double copysign(double x,
        double y)
    {
        return sign(y) * fabs(x);
    }

    internal static double3x3 scale_matrix_diagonal_f33_f3(double3x3 A,
        double3 v)
    {
        double3x3 B = A;
        B[0][0] = A[0][0] * v[0];
        B[1][1] = A[1][1] * v[1];
        B[2][2] = A[2][2] * v[2];
        return B;
    }

    internal static double lerp(double a, double b, double t)
    {
        return a + t * (b - a);
    }

    internal static double3 lerp_f3(double3 a, double3 b, double t)
    {
        double3 lerped = new double3(lerp(a[0], b[0], t),
            lerp(a[1], b[1], t),
            lerp(a[2], b[2], t));
        return lerped;
    }

    internal static double radians_to_degrees(double radians)
    {
        return radians * 180.0 / M_PI;
    }

    internal static double degrees_to_radians(double degrees)
    {
        return degrees / 180.0 * M_PI;
    }

    internal static double3x3 RGBtoXYZ_f33(in Chromaticities C,
        double Y)
    {
        double X = C.white[0] * Y / C.white[1];
        double Z = (1.0 - C.white[0] - C.white[1]) * Y / C.white[1];

        double d = C.red[0] * (C.blue[1] - C.green[1]) +
            C.blue[0] * (C.green[1] - C.red[1]) +
            C.green[0] * (C.red[1] - C.blue[1]);

        double Sr = (X * (C.blue[1] - C.green[1]) -
            C.green[0] * (Y * (C.blue[1] - 1) + C.blue[1] * (X + Z)) +
            C.blue[0] * (Y * (C.green[1] - 1) + C.green[1] * (X + Z))) /
            d;

        double Sg = (X * (C.red[1] - C.blue[1]) +
            C.red[0] * (Y * (C.blue[1] - 1) + C.blue[1] * (X + Z)) -
            C.blue[0] * (Y * (C.red[1] - 1) + C.red[1] * (X + Z))) /
            d;

        double Sb = (X * (C.green[1] - C.red[1]) -
            C.red[0] * (Y * (C.green[1] - 1) + C.green[1] * (X + Z)) +
            C.green[0] * (Y * (C.red[1] - 1) + C.red[1] * (X + Z))) /
            d;

        double3x3 M = default;

        M[0][0] = Sr * C.red[0];
        M[0][1] = Sr * C.red[1];
        M[0][2] = Sr * (1.0 - C.red[0] - C.red[1]);

        M[1][0] = Sg * C.green[0];
        M[1][1] = Sg * C.green[1];
        M[1][2] = Sg * (1.0 - C.green[0] - C.green[1]);

        M[2][0] = Sb * C.blue[0];
        M[2][1] = Sb * C.blue[1];
        M[2][2] = Sb * (1.0 - C.blue[0] - C.blue[1]);

        return M;
    }

    internal static double3x3 XYZtoRGB_f33(in Chromaticities C,
        double Y)
    {
        return invert_f33(RGBtoXYZ_f33(C, Y));
    }

    internal struct TSParams
    {
        internal double n;
        internal double n_r;
        internal double g;
        internal double t_1;
        internal double c_t;
        internal double s_2;
        internal double u_2;
        internal double m_2;
        internal double forward_limit;
        internal double inverse_limit;
        internal double log_peak;
    }

    internal static TSParams init_TSParams(double peakLuminance)
    {
        double n = peakLuminance;

        double n_r = 100.0;
        double g = 1.15;
        double c = 0.18;
        double c_d = 10.013;
        double w_g = 0.14;
        double t_1 = 0.04;
        double r_hit_min = 128.0;
        double r_hit_max = 896.0;

        double r_hit = r_hit_min + (r_hit_max - r_hit_min) * (log(n / n_r) / log(10000.0 / 100.0));
        double m_0 = (n / n_r);
        double m_1 = 0.5 * (m_0 + sqrt(m_0 * (m_0 + 4.0 * t_1)));
        double u = pow((r_hit / m_1) / ((r_hit / m_1) + 1), g);
        double m = m_1 / u;
        double w_i = log(n / 100.0) / log(2.0);
        double c_t = c_d / n_r * (1.0 + w_i * w_g);
        double g_ip = 0.5 * (c_t + sqrt(c_t * (c_t + 4.0 * t_1)));
        double g_ipp2 = -(m_1 * pow((g_ip / m), (1.0 / g))) / (pow(g_ip / m, 1.0 / g) - 1.0);
        double w_2 = c / g_ipp2;
        double s_2 = w_2 * m_1;
        double u_2 = pow((r_hit / m_1) / ((r_hit / m_1) + w_2), g);
        double m_2 = m_1 / u_2;

        TSParams p = default;
        p.n = n;
        p.n_r = n_r;
        p.g = g;
        p.t_1 = t_1;
        p.c_t = c_t;
        p.s_2 = s_2;
        p.u_2 = u_2;
        p.m_2 = m_2;
        p.forward_limit = 8.0 * r_hit;
        p.inverse_limit = n / (u_2 * n_r);
        p.log_peak = log10(n / n_r);

        return p;
    }

    internal static double tonescale_fwd(double x,
        in TSParams @params
        )
    {
        double f = @params.m_2 * pow(max(0.0, x) / (x + @params.s_2), @params.g);
        double h = max(0.0, f * f / (f + @params.t_1));

        return h * @params.n_r;
    }

    internal struct JMhParams
    {
        internal double3x3 MATRIX_RGB_to_CAM16_c;
        internal double3x3 MATRIX_CAM16_c_to_RGB;
        internal double3x3 MATRIX_cone_response_to_Aab;
        internal double3x3 MATRIX_Aab_to_cone_response;
        internal double F_L_n;
        internal double cz;
        internal double inv_cz;
        internal double A_w_J;
        internal double inv_A_w_J;
    }

    internal struct HueDependentGamutParams
    {
        internal double2 JMcusp;
        internal double gamma_bottom_inv;
        internal double gamma_top_inv;
        internal double focus_J;
        internal double analytical_threshold;
    }

    internal struct ODTParams
    {
        internal double peakLuminance;
        internal JMhParams input_params;
        internal JMhParams reach_params;
        internal JMhParams limit_params;
        internal TSParams ts;
        internal double limit_J_max;
        internal double model_gamma_inv;
        internal NativeArray<double> TABLE_reach_M;
        internal double sat;
        internal double sat_thr;
        internal double compr;
        internal double chroma_compress_scale;
        internal double mid_J;
        internal double focus_dist;
        internal double lower_hull_gamma_inv;
        internal NativeArray<double> TABLE_hues;
        internal NativeArray<double3> TABLE_gamut_cusps;
        internal NativeArray<double> TABLE_upper_hull_gamma;
        internal int2 hue_linearity_search_range;

        internal static ODTParams Create()
        {
            ODTParams r = default;
            r.TABLE_reach_M = new NativeArray<double>(totalTableSize, Allocator.Temp);
            r.TABLE_hues = new NativeArray<double>(totalTableSize, Allocator.Temp);
            r.TABLE_gamut_cusps = new NativeArray<double3>(totalTableSize, Allocator.Temp);
            r.TABLE_upper_hull_gamma = new NativeArray<double>(totalTableSize, Allocator.Temp);
            return r;
        }
    }

    internal struct TestData
    {
        internal double3 test_JMh;
        internal double J_intersect_source;
        internal double slope;
        internal double J_intersect_cusp;
    }

    internal static double wrap_to_360(double hue)
    {
        double y = fmod(hue, 360.0);
        if (y < 0.0)
        {
            y = y + 360.0;
        }
        return y;
    }

    internal static int hue_position_in_uniform_table(double hue, int table_size)
    {
        double wrapped_hue = wrap_to_360(hue);
        int result = (int)(wrapped_hue / hue_limit * table_size);
        return result;
    }

    internal static double base_hue_for_position(int i_lo, int table_size)
    {
        double result = i_lo * hue_limit / table_size;
        return result;
    }

    internal static double _post_adaptation_cone_response_compression_fwd(double Rc)
    {
        double F_L_Y = pow(Rc, 0.42);
        double Ra = (F_L_Y) / (cam_nl_offset + F_L_Y);
        return Ra;
    }

    internal static double _post_adaptation_cone_response_compression_inv(double Ra)
    {
        double Ra_lim = min(Ra, 0.99);
        double F_L_Y = (cam_nl_offset * Ra_lim) / (1.0 - Ra_lim);
        double Rc = pow(F_L_Y, 1.0 / 0.42);
        return Rc;
    }

    internal static double post_adaptation_cone_response_compression_fwd(double v)
    {
        double abs_v = fabs(v);
        double Ra = _post_adaptation_cone_response_compression_fwd(abs_v);
        return copysign(Ra, v);
    }

    internal static double post_adaptation_cone_response_compression_inv(double v)
    {
        double abs_v = fabs(v);
        double Rc = _post_adaptation_cone_response_compression_inv(abs_v);
        return copysign(Rc, v);
    }

    internal static double Achromatic_n_to_J(double A,
        double cz)
    {
        return J_scale * pow(A, cz);
    }

    internal static double J_to_Achromatic_n(double J,
        double inv_cz)
    {
        return pow(J * (1.0 / J_scale), inv_cz);
    }

    internal static double _A_to_Y(double A,
        in JMhParams p)
    {
        double Ra = p.A_w_J * A;
        double Y = _post_adaptation_cone_response_compression_inv(Ra) / p.F_L_n;

        return Y;
    }

    internal static double J_to_Y(double J,
        in JMhParams p)
    {
        double abs_J = fabs(J);

        return _A_to_Y(J_to_Achromatic_n(abs_J, p.inv_cz), p);
    }

    internal static double Y_to_J(double Y,
        in JMhParams p)
    {
        double abs_Y = fabs(Y);
        double Ra = _post_adaptation_cone_response_compression_fwd(abs_Y * p.F_L_n);
        double J = Achromatic_n_to_J(Ra * p.inv_A_w_J, p.cz);

        return copysign(J, Y);
    }

    internal static double3 RGB_to_Aab(double3 RGB,
        in JMhParams p)
    {
        double3 rgb_m = mult_f3_f33(RGB, p.MATRIX_RGB_to_CAM16_c);

        double3 rgb_a = new double3(
            post_adaptation_cone_response_compression_fwd(rgb_m[0]),
            post_adaptation_cone_response_compression_fwd(rgb_m[1]),
            post_adaptation_cone_response_compression_fwd(rgb_m[2]));

        double3 Aab = mult_f3_f33(rgb_a, p.MATRIX_cone_response_to_Aab);

        return Aab;
    }

    internal static double3 Aab_to_JMh(double3 Aab,
        in JMhParams p)
    {
        double3 JMh = new double3(0.0, 0.0, 0.0);
        if (Aab[0] <= 0.0)
        {
            return JMh;
        }
        double J = Achromatic_n_to_J(Aab[0], p.cz);
        double M = sqrt(Aab[1] * Aab[1] + Aab[2] * Aab[2]);
        double h_rad = atan2(Aab[2], Aab[1]);
        double h = wrap_to_360(radians_to_degrees(h_rad));

        JMh[0] = J;
        JMh[1] = M;
        JMh[2] = h;

        return JMh;
    }

    internal static double3 RGB_to_JMh(double3 RGB,
        in JMhParams p)
    {
        double3 Aab = RGB_to_Aab(RGB, p);
        double3 JMh = Aab_to_JMh(Aab, p);

        return JMh;
    }

    internal static double3 JMh_to_Aab(double3 JMh,
        in JMhParams p)
    {
        double J = JMh[0];
        double M = JMh[1];
        double h = JMh[2];
        double h_rad = degrees_to_radians(h);
        double cos_hr = cos(h_rad);
        double sin_hr = sin(h_rad);

        double A = J_to_Achromatic_n(J, p.inv_cz);
        double a = M * cos_hr;
        double b = M * sin_hr;
        double3 Aab = new double3(A, a, b);

        return Aab;
    }

    internal static double3 Aab_to_RGB(double3 Aab,
        in JMhParams p)
    {
        double3 rgb_a = mult_f3_f33(Aab, p.MATRIX_Aab_to_cone_response);

        double3 rgb_m = new double3(
            post_adaptation_cone_response_compression_inv(rgb_a[0]),
            post_adaptation_cone_response_compression_inv(rgb_a[1]),
            post_adaptation_cone_response_compression_inv(rgb_a[2]));

        double3 rgb = mult_f3_f33(rgb_m, p.MATRIX_CAM16_c_to_RGB);

        return rgb;
    }

    internal static double3 JMh_to_RGB(double3 JMh,
        in JMhParams p)
    {
        double3 Aab = JMh_to_Aab(JMh, p);
        double3 rgb = Aab_to_RGB(Aab, p);
        return rgb;
    }

    internal static double3 clamp_AP0_to_AP1(double3 aces,
        double clamp_lower_limit,
        double clamp_upper_limit)
    {
        double3 AP1 = mult_f3_f33(aces, AP0_TO_AP1);
        double3 AP1_clamped = clamp_f3(AP1, clamp_lower_limit, clamp_upper_limit);
        double3 AP0_clamped = mult_f3_f33(AP1_clamped, AP1_TO_AP0);

        return AP0_clamped;
    }

    internal static double reach_M_from_table(double h,
        NativeArray<double> table)
    {
        int @base = hue_position_in_uniform_table(h, tableSize);
        double t = h - @base;
        int i_lo = @base + baseIndex;
        int i_hi = i_lo + 1;

        return lerp(table[i_lo], table[i_hi], t);
    }

    internal static double reinhard_remap(double scale,
        double nd,
        bool invert = false)
    {
        if (invert)
        {
            if (nd >= 1.0)
            {
                return scale;
            }
            else
            {
                return scale * -(nd / (nd - 1.0));
            }
        }
        return scale * nd / (1.0 + nd);
    }

    internal static double midpoint(double low, double high)
    {
        return (low + high) / 2.0;
    }

    internal static double toe(double x,
        double limit,
        double k1_in,
        double k2_in,
        bool invert = false)
    {
        if (x > limit)
            return x;

        double k2 = max(k2_in, 0.001);
        double k1 = sqrt(k1_in * k1_in + k2 * k2);
        double k3 = (limit + k1) / (limit + k2);

        if (invert)
        {
            return (x * x + k1 * x) / (k3 * (x + k2));
        }
        else
        {
            double minus_b = k3 * x - k1;
            double minus_c = k2 * k3 * x;
            return 0.5 * (minus_b + sqrt(minus_b * minus_b + 4.0 * minus_c));
        }
    }

    internal static double chroma_compress_norm(double h,
        double chroma_compress_scale)
    {
        double hr = degrees_to_radians(h);

        double a = cos(hr);
        double b = sin(hr);
        double cos_hr2 = a * a - b * b;
        double sin_hr2 = 2.0 * a * b;
        double cos_hr3 = 4.0 * a * a * a - 3.0 * a;
        double sin_hr3 = 3.0 * b - 4.0 * b * b * b;

        double M = 11.34072 * a +
            16.46899 * cos_hr2 +
            7.88380 * cos_hr3 +
            14.66441 * b +
            -6.37224 * sin_hr2 +
            9.19364 * sin_hr3 +
            77.12896;

        return M * chroma_compress_scale;
    }

    internal static double3 chroma_compress_fwd(double3 JMh,
        double tonemapped_J,
        in ODTParams p,
        bool invert = false)
    {
        double J = JMh[0];
        double M = JMh[1];
        double h = JMh[2];

        double M_compr = M;

        if (M != 0.0)
        {
            double nJ = tonemapped_J / p.limit_J_max;
            double snJ = max(0.0, 1.0 - nJ);
            double Mnorm = chroma_compress_norm(h, p.chroma_compress_scale);
            double limit = pow(nJ, p.model_gamma_inv) * reach_M_from_table(h, p.TABLE_reach_M) / Mnorm;

            double toe_limit = limit - 0.001;
            double toe_snJ_sat = snJ * p.sat;
            double toe_sqrt_nJ_sat_thr = sqrt(nJ * nJ + p.sat_thr);
            double toe_nJ_compr = nJ * p.compr;

            M_compr = M * pow(tonemapped_J / J, p.model_gamma_inv);

            M_compr = M_compr / Mnorm;

            M_compr = limit - toe(limit - M_compr, toe_limit, toe_snJ_sat, toe_sqrt_nJ_sat_thr, false);

            M_compr = toe(M_compr, limit, toe_nJ_compr, snJ, false);

            M_compr = M_compr * Mnorm;
        }

        double3 @out = new double3(tonemapped_J, M_compr, h);
        return @out;
    }

    internal static double3 tonemap_and_compress_fwd(double3 JMh,
        in ODTParams p)
    {
        double linear = J_to_Y(JMh[0], p.input_params) / ref_luminance;

        double tonemapped_Y = tonescale_fwd(linear, p.ts);

        double J_ts = Y_to_J(tonemapped_Y, p.input_params);

        double3 JMh_tc = chroma_compress_fwd(JMh, J_ts, p, false);

        return JMh_tc;
    }

    internal static double compute_compression_vector_slope(double intersect_J,
        double focus_J,
        double limit_J_max,
        double slope_gain)
    {
        double direction_scalar = default;
        if (intersect_J < focus_J)
        {
            direction_scalar = intersect_J;
        }
        else
        {
            direction_scalar = limit_J_max - intersect_J;
        }
        return direction_scalar * (intersect_J - focus_J) / (focus_J * slope_gain);
    }

    internal static double solve_J_intersect(double J,
        double M,
        double focusJ,
        double maxJ,
        double slope_gain)
    {
        double M_scaled = M / slope_gain;
        double a = M_scaled / focusJ;

        if (J < focusJ)
        {
            double b = 1.0 - M_scaled;
            double c = -J;
            double det = b * b - 4.0 * a * c;
            double root = sqrt(det);
            return -2.0 * c / (b + root);
        }
        else
        {
            double b = -(1.0 + M_scaled + maxJ * a);
            double c = maxJ * M_scaled + J;
            double det = b * b - 4.0 * a * c;
            double root = sqrt(det);
            return -2.0 * c / (b - root);
        }
    }

    internal static double smin_scaled(double a,
        double b,
        double scale_reference)
    {
        double s_scaled = smooth_cusps * scale_reference;
        double h = max(s_scaled - fabs(a - b), 0.0) / s_scaled;
        return min(a, b) - h * h * h * s_scaled * (1.0 / 6.0);
    }

    internal static double estimate_line_and_boundary_intersection_M(double J_axis_intersect,
        double slope,
        double inv_gamma,
        double J_max,
        double M_max,
        double J_intersection_reference)
    {
        double normalised_J = J_axis_intersect / J_intersection_reference;
        double shifted_intersection = J_intersection_reference * pow(normalised_J, inv_gamma);

        return shifted_intersection * M_max / (J_max - slope * M_max);
    }

    internal static double find_gamut_boundary_intersection(double2 JM_cusp,
        double J_max,
        double gamma_top_inv,
        double gamma_bottom_inv,
        double J_intersect_source,
        double slope,
        double J_intersect_cusp)
    {
        double M_boundary_lower = estimate_line_and_boundary_intersection_M(J_intersect_source,
            slope,
            gamma_bottom_inv,
            JM_cusp[0],
            JM_cusp[1],
            J_intersect_cusp);

        double f_J_intersect_cusp = J_max - J_intersect_cusp;
        double f_J_intersect_source = J_max - J_intersect_source;
        double f_JM_cusp_J = J_max - JM_cusp[0];
        double M_boundary_upper = estimate_line_and_boundary_intersection_M(f_J_intersect_source,
            -slope,
            gamma_top_inv,
            f_JM_cusp_J,
            JM_cusp[1],
            f_J_intersect_cusp);

        double M_boundary = smin_scaled(M_boundary_lower, M_boundary_upper, JM_cusp[1]);
        return M_boundary;
    }

    internal static double get_focus_gain(double J,
        double analytical_threshold,
        double limit_J_max,
        double focus_dist)
    {
        double gain = limit_J_max * focus_dist;

        if (J > analytical_threshold)
        {
            double gain_adjustment = log10((limit_J_max - analytical_threshold) / max(0.0001, limit_J_max - J));
            gain_adjustment = gain_adjustment * gain_adjustment + 1.0;
            gain = gain * gain_adjustment;
        }

        return gain;
    }

    internal static double remap_M(double M,
        double gamut_boundary_M,
        double reach_boundary_M,
        bool invert = false)
    {
        double boundary_ratio = gamut_boundary_M / reach_boundary_M;
        double proportion = max(boundary_ratio, compression_threshold);
        double threshold = proportion * gamut_boundary_M;

        if (M <= threshold || proportion >= 1.0)
            return M;

        double m_offset = M - threshold;
        double gamut_offset = gamut_boundary_M - threshold;
        double reach_offset = reach_boundary_M - threshold;

        double scale = reach_offset / ((reach_offset / gamut_offset) - 1.0);
        double nd = m_offset / scale;

        return threshold + reinhard_remap(scale, nd, invert);
    }

    internal static double3 compress_gamut(double3 JMh,
        double Jx,
        in ODTParams p,
        in HueDependentGamutParams hdp,
        bool invert = false)
    {
        double J = JMh[0];
        double M = JMh[1];
        double h = JMh[2];

        double slope_gain = get_focus_gain(Jx, hdp.analytical_threshold, p.limit_J_max, p.focus_dist);
        double J_intersect_source = solve_J_intersect(J, M, hdp.focus_J, p.limit_J_max, slope_gain);
        double gamut_slope = compute_compression_vector_slope(J_intersect_source, hdp.focus_J, p.limit_J_max, slope_gain);

        double J_intersect_cusp = solve_J_intersect(hdp.JMcusp[0], hdp.JMcusp[1], hdp.focus_J, p.limit_J_max, slope_gain);

        double gamut_boundary_M = find_gamut_boundary_intersection(hdp.JMcusp,
            p.limit_J_max,
            hdp.gamma_top_inv,
            hdp.gamma_bottom_inv,
            J_intersect_source,
            gamut_slope,
            J_intersect_cusp);

        if (gamut_boundary_M <= 0.0)
        {
            double3 returnJMh = new double3(J, 0.0, h);
            return returnJMh;
        }

        double reach_max_M = reach_M_from_table(h, p.TABLE_reach_M);

        double reach_boundary_M = estimate_line_and_boundary_intersection_M(J_intersect_source,
            gamut_slope,
            p.model_gamma_inv,
            p.limit_J_max,
            reach_max_M,
            p.limit_J_max);

        double remapped_M = remap_M(M, gamut_boundary_M, reach_boundary_M, invert);

        double3 JMhcompressed = new double3(J_intersect_source + remapped_M * gamut_slope,
            remapped_M,
            h);

        return JMhcompressed;
    }

    internal static double2 cusp_from_table(double h,
        NativeArray<double3> table)
    {
        double3 lo = default;
        double3 hi = default;

        int low_i = 0;
        int high_i = baseIndex + tableSize;
        int i = hue_position_in_uniform_table(h, tableSize) + baseIndex;

        while (low_i + 1 < high_i)
        {
            if (h > table[i][2])
            {
                low_i = i;
            }
            else
            {
                high_i = i;
            }
            i = (int)midpoint(low_i, high_i);
        }
        lo = table[high_i - 1];
        hi = table[high_i];

        double t = (h - lo[2]) / (hi[2] - lo[2]);
        double cusp_J = lerp(lo[0], hi[0], t);
        double cusp_M = lerp(lo[1], hi[1], t);

        double2 cusp_JM = new double2(cusp_J, cusp_M);

        return cusp_JM;
    }

    internal static int lookup_hue_interval(double h,
        NativeArray<double> hue_table,
        int2 hue_linearity_search_range)
    {
        int i = baseIndex + hue_position_in_uniform_table(h, totalTableSize);
        int i_lo = max(baseIndex, i + hue_linearity_search_range[0]);
        int i_hi = min(baseIndex + tableSize, i + hue_linearity_search_range[1]);

        while (i_lo + 1 < i_hi)
        {
            if (h > hue_table[i])
            {
                i_lo = i;
            }
            else
            {
                i_hi = i;
            }
            i = (int)midpoint(i_lo, i_hi);
        }

        i_hi = max(1, i_hi);

        return i_hi;
    }

    internal static double interpolation_weight(double h, double h_lo, double h_hi)
    {
        return (h - h_lo);
    }

    internal static double compute_focus_J(double cusp_J, double mid_J, double limit_J_max)
    {
        return lerp(cusp_J, mid_J, min(1, cusp_mid_blend - (cusp_J / limit_J_max)));
    }

    internal static HueDependentGamutParams init_HueDependentGamutParams(double hue, in ODTParams p)
    {
        HueDependentGamutParams hdp = default;
        hdp.gamma_bottom_inv = p.lower_hull_gamma_inv;

        int i_hi = lookup_hue_interval(hue, p.TABLE_hues, p.hue_linearity_search_range);
        double t = interpolation_weight(hue, p.TABLE_hues[i_hi - 1], p.TABLE_hues[i_hi]);

        hdp.JMcusp = cusp_from_table(hue, p.TABLE_gamut_cusps);
        hdp.gamma_top_inv = lerp(p.TABLE_upper_hull_gamma[i_hi - 1], p.TABLE_upper_hull_gamma[i_hi], t);
        hdp.focus_J = compute_focus_J(hdp.JMcusp[0], p.mid_J, p.limit_J_max);
        hdp.analytical_threshold = lerp(hdp.JMcusp[0], p.limit_J_max, focus_gain_blend);

        return hdp;
    }

    internal static double3 gamut_compress_fwd(double3 JMh,
        in ODTParams p)
    {
        double J = JMh[0];
        double M = JMh[1];
        double h = JMh[2];

        if (J <= 0.0)
        {
            return new double3(0.0, 0.0, h);
        }

        if (M < 0.0 || J > p.limit_J_max)
        {
            return new double3(J, 0.0, h);
        }

        HueDependentGamutParams hdp = init_HueDependentGamutParams(h, p);

        return compress_gamut(JMh, J, p, hdp, false);
    }

    internal static bool any_below_zero(double3 newLimitRGB)
    {
        return (newLimitRGB[0] < 0.0 || newLimitRGB[1] < 0.0 || newLimitRGB[2] < 0.0);
    }

    internal static JMhParams init_JMhParams(in Chromaticities prims)
    {
        Chromaticities CAM16_PRI = new Chromaticities {red=new double2(0.8336, 0.1735), green=new double2(2.3854, -1.4659), blue=new double2(0.087, -0.125), white=new double2(0.333, 0.333)};

        double3x3 MATRIX_16 = XYZtoRGB_f33(CAM16_PRI, 1.0);

        double3x3 base_cone_response_to_Aab = new double3x3(new double3(2.0, 1.0, 1.0 / 9.0), new double3(1.0, -12.0 / 11.0, 1.0 / 9.0), new double3(1.0 / 20.0, 1.0 / 11.0, -2.0 / 9.0));

        double3x3 RGB_TO_XYZ = RGBtoXYZ_f33(prims, 1.0);
        double3 XYZ_w = mult_f3_f33(f3_from_f(ref_luminance), RGB_TO_XYZ);

        double Y_w = XYZ_w[1];

        double3 RGB_w = mult_f3_f33(XYZ_w, MATRIX_16);

        double k = 1.0 / (5.0 * L_A + 1.0);
        double k4 = k * k * k * k;
        double F_L = 0.2 * k4 * (5.0 * L_A) + 0.1 * pow((1.0 - k4), 2.0) * pow(5.0 * L_A, 1.0 / 3.0);

        double F_L_n = F_L / ref_luminance;
        double cz = model_gamma;

        double3 D_RGB = new double3(
            F_L_n * Y_w / RGB_w[0],
            F_L_n * Y_w / RGB_w[1],
            F_L_n * Y_w / RGB_w[2]);

        double3 RGB_wc = new double3(
            D_RGB[0] * RGB_w[0],
            D_RGB[1] * RGB_w[1],
            D_RGB[2] * RGB_w[2]);

        double3 RGB_Aw = new double3(
            post_adaptation_cone_response_compression_fwd(RGB_wc[0]),
            post_adaptation_cone_response_compression_fwd(RGB_wc[1]),
            post_adaptation_cone_response_compression_fwd(RGB_wc[2]));

        double3x3 cone_response_to_Aab = mult_f33_f33(mult_f_f33(cam_nl_scale, MATRIX_IDENTITY), base_cone_response_to_Aab);
        double A_w = cone_response_to_Aab[0][0] * RGB_Aw[0] + cone_response_to_Aab[1][0] * RGB_Aw[1] + cone_response_to_Aab[2][0] * RGB_Aw[2];
        double A_w_J = _post_adaptation_cone_response_compression_fwd(F_L);

        double3x3 M1 = mult_f33_f33(RGB_TO_XYZ, MATRIX_16);
        double3x3 M2 = mult_f_f33(ref_luminance, MATRIX_IDENTITY);
        double3x3 MATRIX_RGB_to_CAM16 = mult_f33_f33(M1, M2);
        double3x3 MATRIX_RGB_to_CAM16_c = mult_f33_f33(MATRIX_RGB_to_CAM16, scale_matrix_diagonal_f33_f3(MATRIX_IDENTITY, D_RGB));

        double3x3 MATRIX_cone_response_to_Aab = new double3x3(new double3(cone_response_to_Aab[0][0] / A_w, cone_response_to_Aab[0][1] * 43.0 * surround[2], cone_response_to_Aab[0][2] * 43.0 * surround[2]), new double3(cone_response_to_Aab[1][0] / A_w, cone_response_to_Aab[1][1] * 43.0 * surround[2], cone_response_to_Aab[1][2] * 43.0 * surround[2]), new double3(cone_response_to_Aab[2][0] / A_w, cone_response_to_Aab[2][1] * 43.0 * surround[2], cone_response_to_Aab[2][2] * 43.0 * surround[2]));

        JMhParams p = default;
        p.MATRIX_RGB_to_CAM16_c = MATRIX_RGB_to_CAM16_c;
        p.MATRIX_CAM16_c_to_RGB = invert_f33(MATRIX_RGB_to_CAM16_c);
        p.MATRIX_cone_response_to_Aab = MATRIX_cone_response_to_Aab;
        p.MATRIX_Aab_to_cone_response = invert_f33(MATRIX_cone_response_to_Aab);
        p.F_L_n = F_L_n;
        p.cz = cz;
        p.inv_cz = 1.0 / cz;
        p.A_w_J = A_w_J;
        p.inv_A_w_J = 1.0 / A_w_J;

        return p;
    }

    internal static double3 generate_unit_cube_cusp_corners(int corner)
    {
        double3 result = default;

        if (((corner + 1) % cuspCornerCount) < 3)
            result[0] = 1;
        else
            result[0] = 0;
        if (((corner + 5) % cuspCornerCount) < 3)
            result[1] = 1;
        else
            result[1] = 0;
        if (((corner + 3) % cuspCornerCount) < 3)
            result[2] = 1;
        else
            result[2] = 0;

        return result;
    }

    internal static void build_limiting_cusp_corners_tables(NativeArray<double3> RGB_corners,
        NativeArray<double3> JMh_corners,
        in JMhParams @params,
        double peakLuminance)
    {
        NativeArray<double3> temp_RGB_corners = new NativeArray<double3>(cuspCornerCount, Allocator.Temp);
        NativeArray<double3> temp_JMh_corners = new NativeArray<double3>(cuspCornerCount, Allocator.Temp);

        int min_index = 0;
        for (int i = 0; i != cuspCornerCount; i = i + 1)
        {
            temp_RGB_corners[i] = mult_f_f3(peakLuminance / ref_luminance, generate_unit_cube_cusp_corners(i));
            temp_JMh_corners[i] = RGB_to_JMh(temp_RGB_corners[i], @params);
            if (temp_JMh_corners[i][2] < temp_JMh_corners[min_index][2])
                min_index = i;
        }

        for (int i = 0; i != cuspCornerCount; i = i + 1)
        {
            RGB_corners[i + 1] = temp_RGB_corners[(i + min_index) % cuspCornerCount];
            JMh_corners[i + 1] = temp_JMh_corners[(i + min_index) % cuspCornerCount];
        }

        RGB_corners[0] = RGB_corners[cuspCornerCount];
        RGB_corners[cuspCornerCount + 1] = RGB_corners[1];
        JMh_corners[0] = JMh_corners[cuspCornerCount];
        JMh_corners[cuspCornerCount + 1] = JMh_corners[1];

        JMh_corners[0] = With(JMh_corners[0], 2, JMh_corners[0][2] - hue_limit);
        JMh_corners[cuspCornerCount + 1] = With(JMh_corners[cuspCornerCount + 1], 2, JMh_corners[cuspCornerCount + 1][2] + hue_limit);
    }

    internal static NativeArray<double3> find_reach_corners_table(in JMhParams params_reach,
        in ODTParams p)
    {
        NativeArray<double3> temp_JMh_corners = new NativeArray<double3>(cuspCornerCount, Allocator.Temp);

        NativeArray<double3> JMh_corners = new NativeArray<double3>(totalCornerCount, Allocator.Temp);

        double limitA = J_to_Achromatic_n(p.limit_J_max, params_reach.inv_cz);

        int min_index = 0;
        for (int i = 0; i != cuspCornerCount; i = i + 1)
        {
            double3 rgb_vector = generate_unit_cube_cusp_corners(i);

            double lower = 0.0;
            double upper = p.ts.forward_limit;

            while ((upper - lower) > reach_cusp_tolerance)
            {
                double test = (lower + upper) / 2.0;
                double3 test_corner = mult_f_f3(test, rgb_vector);
                double A = RGB_to_Aab(test_corner, params_reach)[0];
                if (A < limitA)
                {
                    lower = test;
                }
                else
                {
                    upper = test;
                }
            }

            temp_JMh_corners[i] = RGB_to_JMh(mult_f_f3(upper, rgb_vector), params_reach);

            if (temp_JMh_corners[i][2] < temp_JMh_corners[min_index][2])
                min_index = i;
        }

        for (int i = 0; i != cuspCornerCount; i = i + 1)
        {
            JMh_corners[i + 1] = temp_JMh_corners[(i + min_index) % cuspCornerCount];
        }

        JMh_corners[0] = JMh_corners[cuspCornerCount];
        JMh_corners[cuspCornerCount + 1] = JMh_corners[1];

        JMh_corners[0] = With(JMh_corners[0], 2, JMh_corners[0][2] - hue_limit);
        JMh_corners[cuspCornerCount + 1] = With(JMh_corners[cuspCornerCount + 1], 2, JMh_corners[cuspCornerCount + 1][2] + hue_limit);

        return JMh_corners;
    }

    internal static NativeArray<double> extract_sorted_cube_hues(NativeArray<double3> reach_JMh,
        NativeArray<double3> limit_JMh)
    {
        NativeArray<double> sorted_hues = new NativeArray<double>(max_sorted_corners, Allocator.Temp);

        int idx = 0;
        int reach_idx = 1;
        int limit_idx = 1;
        while ((reach_idx < (cuspCornerCount + 1)) || (limit_idx < (cuspCornerCount + 1)))
        {
            double reach_hue = reach_JMh[reach_idx][2];
            double limit_hue = limit_JMh[limit_idx][2];
            if (reach_hue == limit_hue)
            {
                sorted_hues[idx] = reach_hue;
                reach_idx = reach_idx + 1;
                limit_idx = limit_idx + 1;
            }
            else
            {
                if (reach_hue < limit_hue)
                {
                    sorted_hues[idx] = reach_hue;
                    reach_idx = reach_idx + 1;
                }
                else
                {
                    sorted_hues[idx] = limit_hue;
                    limit_idx = limit_idx + 1;
                }
            }
            idx = idx + 1;
        }
        return sorted_hues;
    }

    internal static NativeArray<double> build_hue_sample_interval(int samples,
        double lower,
        double upper,
        NativeArray<double> hue_table,
        int @base)
    {
        NativeArray<double> mod_hue_table = Copy(hue_table);
        double delta = (upper - lower) / samples;
        int i = default;
        for (i = 0; i != samples; i = i + 1)
        {
            mod_hue_table[@base + i] = lower + i * delta;
        }

        return mod_hue_table;
    }

    internal static NativeArray<double> build_hue_table(NativeArray<double> sorted_hues)
    {
        NativeArray<double> hue_table = new NativeArray<double>(totalTableSize, Allocator.Temp);

        double ideal_spacing = tableSize / hue_limit;
        NativeArray<int> samples_count = new NativeArray<int>(2 * cuspCornerCount + 2, Allocator.Temp);
        int last_idx = default;
        int min_index = default;
        if (sorted_hues[0] == 0.0)
        {
            min_index = 0;
        }
        else
        {
            min_index = 1;
        }
        int hue_idx = default;

        for (hue_idx = 0; hue_idx != max_sorted_corners; hue_idx = hue_idx + 1)
        {
            double raw_idx = round(sorted_hues[hue_idx] * ideal_spacing);
            int nominal_idx = (int)(min(max(round(sorted_hues[hue_idx] * ideal_spacing), min_index), tableSize - 1));

            if (last_idx == nominal_idx)
            {
                if (hue_idx > 1 && samples_count[hue_idx - 2] != (samples_count[hue_idx - 1] - 1))
                {
                    samples_count[hue_idx - 1] = samples_count[hue_idx - 1] - 1;
                }
                else
                {
                    nominal_idx = nominal_idx + 1;
                }
            }
            samples_count[hue_idx] = min(nominal_idx, tableSize - 1);
            min_index = nominal_idx;
            last_idx = min_index;
        }

        int total_samples = 0;

        int i = 0;
        hue_table = build_hue_sample_interval(samples_count[i], 0.0, sorted_hues[i], hue_table, total_samples + 1);
        total_samples = total_samples + samples_count[i];

        for (i = i + 1; i != max_sorted_corners; i = i + 1)
        {
            int samples = samples_count[i] - samples_count[i - 1];
            hue_table = build_hue_sample_interval(samples, sorted_hues[i - 1], sorted_hues[i], hue_table, total_samples + 1);
            total_samples = total_samples + samples;
        }
        hue_table = build_hue_sample_interval(tableSize - total_samples, sorted_hues[i - 1], hue_limit, hue_table, total_samples + 1);

        hue_table[0] = hue_table[baseIndex + tableSize - 1] - hue_limit;
        hue_table[baseIndex + tableSize] = hue_table[baseIndex] + hue_limit;

        return hue_table;
    }

    internal static double2 find_display_cusp_for_hue(double hue,
        NativeArray<double3> RGB_corners,
        NativeArray<double3> JMh_corners,
        in JMhParams @params,
        double2 previous)
    {
        double2 return_JM = default;

        int upper_corner = 1;
        int found = 0;
        for (int i = upper_corner; i != totalCornerCount && found == 0; i = i + 1)
        {
            if (JMh_corners[i][2] > hue)
            {
                upper_corner = i;
                found = 1;
            }
        }
        int lower_corner = upper_corner - 1;

        if (JMh_corners[lower_corner][2] == hue)
        {
            return_JM[0] = JMh_corners[lower_corner][0];
            return_JM[1] = JMh_corners[lower_corner][1];
            return return_JM;
        }

        double3 cusp_lower = RGB_corners[lower_corner];
        double3 cusp_upper = RGB_corners[upper_corner];
        double3 sample = default;

        double sample_t = default;
        double lower_t = 0.0;
        if (upper_corner == previous[0])
            lower_t = previous[1];
        double upper_t = 1.0;

        double3 JMh = default;

        while ((upper_t - lower_t) > display_cusp_tolerance)
        {
            sample_t = midpoint(lower_t, upper_t);
            sample = lerp_f3(cusp_lower, cusp_upper, sample_t);
            JMh = RGB_to_JMh(sample, @params);
            if (JMh[2] < JMh_corners[lower_corner][2])
            {
                upper_t = sample_t;
            }
            else if (JMh[2] >= JMh_corners[upper_corner][2])
            {
                lower_t = sample_t;
            }
            else if (JMh[2] > hue)
            {
                upper_t = sample_t;
            }
            else
            {
                lower_t = sample_t;
            }
        }

        sample_t = midpoint(lower_t, upper_t);
        sample = lerp_f3(cusp_lower, cusp_upper, sample_t);
        JMh = RGB_to_JMh(sample, @params);

        return_JM[0] = JMh[0];
        return_JM[1] = JMh[1];
        return return_JM;
    }

    internal static void build_cusp_table_entry(int i, NativeArray<double> hue_table,
        NativeArray<double3> RGB_corners,
        NativeArray<double3> JMh_corners,
        in JMhParams @params, double2 previous, NativeArray<double3> output_table)
    {
        double hue = hue_table[i];
        double2 JM = find_display_cusp_for_hue(hue, RGB_corners, JMh_corners, @params, previous);
        output_table[i] = With(output_table[i], 0, JM[0]);
        output_table[i] = With(output_table[i], 1, JM[1] * (1.0 + smooth_m * smooth_cusps));
        output_table[i] = With(output_table[i], 2, hue);
    }

    internal static NativeArray<double3> build_cusp_table(NativeArray<double> hue_table,
        NativeArray<double3> RGB_corners,
        NativeArray<double3> JMh_corners,
        in JMhParams @params)
    {
        double2 previous = new double2(0.0, 0.0);
        NativeArray<double3> output_table = new NativeArray<double3>(totalTableSize, Allocator.Temp);

        for (int i = baseIndex; i != totalTableSize; i = i + 1)
        {
            build_cusp_table_entry(i, hue_table, RGB_corners, JMh_corners, @params, previous, output_table);
        }

        output_table[0] = With(output_table[0], 0, output_table[tableSize][0]);
        output_table[0] = With(output_table[0], 1, output_table[tableSize][1]);
        output_table[0] = With(output_table[0], 2, hue_table[0]);

        output_table[baseIndex + tableSize] = With(output_table[baseIndex + tableSize], 0, output_table[baseIndex][0]);
        output_table[baseIndex + tableSize] = With(output_table[baseIndex + tableSize], 1, output_table[baseIndex][1]);
        output_table[baseIndex + tableSize] = With(output_table[baseIndex + tableSize], 2, hue_table[baseIndex + tableSize]);

        return output_table;
    }

    internal static NativeArray<double3> make_uniform_hue_gamut_table(in JMhParams reach_params,
        in JMhParams limit_params,
        in ODTParams p)
    {
        NativeArray<double3> reach_JMh_corners = new NativeArray<double3>(totalCornerCount, Allocator.Temp);
        NativeArray<double3> limiting_RGB_corners = new NativeArray<double3>(totalCornerCount, Allocator.Temp);
        NativeArray<double3> limiting_JMh_corners = new NativeArray<double3>(totalCornerCount, Allocator.Temp);

        reach_JMh_corners = find_reach_corners_table(reach_params, p);
        build_limiting_cusp_corners_tables(limiting_RGB_corners, limiting_JMh_corners, limit_params, p.peakLuminance);
        NativeArray<double> sorted_hues = extract_sorted_cube_hues(reach_JMh_corners,
            limiting_JMh_corners);

        NativeArray<double> hue_table = build_hue_table(sorted_hues);

        NativeArray<double3> cusp_JMh_table = build_cusp_table(hue_table, limiting_RGB_corners, limiting_JMh_corners, limit_params);

        return cusp_JMh_table;
    }

    internal static void make_reach_m_table_entry(int i, in JMhParams @params,
        double limitJmax, NativeArray<double> reachTable)
    {
        double i_float = i;
        double hue = base_hue_for_position(i, tableSize);

        double search_range = 50.0;
        double search_maximum = 1300.0;
        double low = 0.0;
        double high = low + search_range;
        bool outside = false;

        while ((outside != true) & (high < search_maximum))
        {
            double3 searchJMh = new double3(limitJmax, high, hue);
            double3 newLimitRGB = JMh_to_RGB(searchJMh, @params);
            outside = any_below_zero(newLimitRGB);
            if (outside == false)
            {
                low = high;
                high = high + search_range;
            }
        }

        while (high - low > 1e-2)
        {
            double sampleM = (high + low) / 2.0;
            double3 searchJMh = new double3(limitJmax, sampleM, hue);
            double3 newLimitRGB = JMh_to_RGB(searchJMh, @params);
            outside = any_below_zero(newLimitRGB);
            if (outside)
            {
                high = sampleM;
            }
            else
            {
                low = sampleM;
            }
        }

        reachTable[i + baseIndex] = high;
    }

    internal static NativeArray<double> make_reach_m_table(in JMhParams @params,
        double limitJmax)
    {
        NativeArray<double> reachTable = new NativeArray<double>(totalTableSize, Allocator.Temp);

        for (int i = 0; i < tableSize; i = i + 1)
        {
            make_reach_m_table_entry(i, @params, limitJmax, reachTable);
        }

        reachTable[0] = reachTable[tableSize];

        reachTable[baseIndex + tableSize] = reachTable[baseIndex];

        return reachTable;
    }

    internal static bool outside_hull(double3 rgb, double maxRGBtestVal)
    {
        return rgb[0] > maxRGBtestVal || rgb[1] > maxRGBtestVal || rgb[2] > maxRGBtestVal;
    }

    internal static void generate_gamma_test_data(double2 JMcusp,
        double hue,
        double limit_J_max,
        double mid_J,
        double focus_dist,
        NativeArray<double3> test_JMh,
        NativeArray<double> J_intersect_source,
        NativeArray<double> slopes,
        NativeArray<double> J_intersect_cusp)
    {
        double analytical_threshold = lerp(JMcusp[0], limit_J_max, focus_gain_blend);
        double focus_J = compute_focus_J(JMcusp[0], mid_J, limit_J_max);

        for (int testIndex = 0; testIndex != test_count; testIndex = testIndex + 1)
        {
            double test_J = lerp(JMcusp[0], limit_J_max, testPositions(testIndex));
            double slope_gain = get_focus_gain(test_J, analytical_threshold, limit_J_max, focus_dist);
            double J_intersect = solve_J_intersect(test_J, JMcusp[1], focus_J, limit_J_max, slope_gain);
            double slope = compute_compression_vector_slope(J_intersect, focus_J, limit_J_max, slope_gain);
            double J_cusp = solve_J_intersect(JMcusp[0], JMcusp[1], focus_J, limit_J_max, slope_gain);

            test_JMh[testIndex] = With(test_JMh[testIndex], 0, test_J);
            test_JMh[testIndex] = With(test_JMh[testIndex], 1, JMcusp[1]);
            test_JMh[testIndex] = With(test_JMh[testIndex], 2, hue);
            J_intersect_source[testIndex] = J_intersect;
            slopes[testIndex] = slope;
            J_intersect_cusp[testIndex] = J_cusp;
        }
    }

    internal static bool evaluate_gamma_fit(double2 JMcusp,
        NativeArray<double3> test_JMh,
        NativeArray<double> J_intersect_source,
        NativeArray<double> slopes,
        NativeArray<double> J_intersect_cusp,
        double top_gamma_inv,
        double peakLuminance,
        double limit_J_max,
        double lower_hull_gamma_inv,
        in JMhParams limit_params)
    {
        double luminance_limit = peakLuminance / ref_luminance;

        for (int testIndex = 0; testIndex < test_count; testIndex = testIndex + 1)
        {
            double approxLimit_M = find_gamut_boundary_intersection(JMcusp,
                limit_J_max,
                top_gamma_inv,
                lower_hull_gamma_inv,
                J_intersect_source[testIndex],
                slopes[testIndex],
                J_intersect_cusp[testIndex]);
            double approxLimit_J = J_intersect_source[testIndex] + slopes[testIndex] * approxLimit_M;

            double3 approximate_JMh = new double3(approxLimit_J, approxLimit_M, test_JMh[testIndex][2]);

            double3 newLimitRGB = JMh_to_RGB(approximate_JMh, limit_params);

            if (!outside_hull(newLimitRGB, luminance_limit))
                return false;
        }

        return true;
    }

    internal static void make_upper_hull_gamma_table_entry(int i, NativeArray<double3> gamutCuspTable,
        in ODTParams p, NativeArray<double> upper_hull_gamma)
    {
        double hue = gamutCuspTable[i][2];
        double2 JMcusp = new double2(gamutCuspTable[i][0], gamutCuspTable[i][1]);

        NativeArray<double3> test_JMh = new NativeArray<double3>(test_count, Allocator.Temp);
        NativeArray<double> J_intersect_source = new NativeArray<double>(test_count, Allocator.Temp);
        NativeArray<double> slopes = new NativeArray<double>(test_count, Allocator.Temp);
        NativeArray<double> J_intersect_cusp = new NativeArray<double>(test_count, Allocator.Temp);

        generate_gamma_test_data(JMcusp, hue, p.limit_J_max, p.mid_J, p.focus_dist,
            test_JMh, J_intersect_source, slopes, J_intersect_cusp);

        double search_range = gamma_search_step;
        double low = gamma_minimum;
        double high = low + search_range;
        bool outside = false;
        while (!(outside) && (high < gamma_maximum))
        {
            bool gammaFound = evaluate_gamma_fit(JMcusp,
                test_JMh, J_intersect_source, slopes, J_intersect_cusp,
                1.0 / high,
                p.peakLuminance, p.limit_J_max, p.lower_hull_gamma_inv, p.limit_params);
            if (!gammaFound)
            {
                low = high;
                high = high + search_range;
            }
            else
            {
                outside = true;
            }
        }

        double testGamma = -1.0;
        while ((high - low) > gamma_accuracy)
        {
            testGamma = midpoint(high, low);
            bool gammaFound = evaluate_gamma_fit(JMcusp,
                test_JMh, J_intersect_source, slopes, J_intersect_cusp,
                1.0 / testGamma,
                p.peakLuminance, p.limit_J_max, p.lower_hull_gamma_inv, p.limit_params);
            if (gammaFound)
            {
                high = testGamma;
            }
            else
            {
                low = testGamma;
            }
        }

        upper_hull_gamma[i] = 1.0 / high;
    }

    internal static NativeArray<double> make_upper_hull_gamma_table(NativeArray<double3> gamutCuspTable,
        in ODTParams p)
    {
        NativeArray<double> upper_hull_gamma = new NativeArray<double>(totalTableSize, Allocator.Temp);

        for (int i = baseIndex; i != baseIndex + tableSize; i = i + 1)
        {
            make_upper_hull_gamma_table_entry(i, gamutCuspTable, p, upper_hull_gamma);
        }

        upper_hull_gamma[0] = upper_hull_gamma[tableSize];

        upper_hull_gamma[tableSize + baseIndex] = upper_hull_gamma[baseIndex];

        return upper_hull_gamma;
    }

    internal static int2 determine_hue_linearity_search_range(NativeArray<double> hue_table)
    {
        int lower_padding = 0;
        int upper_padding = 1;

        int2 hue_linearity_search_range = new int2(lower_padding, upper_padding);

        for (int i = baseIndex; i != baseIndex + tableSize; i = i + 1)
        {
            int pos = hue_position_in_uniform_table(hue_table[i], totalTableSize);
            int delta = i - pos;
            hue_linearity_search_range[0] = min(hue_linearity_search_range[0], delta + lower_padding);
            hue_linearity_search_range[1] = max(hue_linearity_search_range[1], delta + upper_padding);
        }

        return hue_linearity_search_range;
    }

    internal static ODTParams init_ODTParams(double peakLuminance,
        in Chromaticities limitingPrimaries)
    {
        ODTParams p = ODTParams.Create();

        p.peakLuminance = peakLuminance;

        p.input_params = init_JMhParams(AP0);
        p.reach_params = init_JMhParams(REACH_PRI);
        p.limit_params = init_JMhParams(limitingPrimaries);

        p.ts = init_TSParams(peakLuminance);

        p.limit_J_max = Y_to_J(peakLuminance, p.input_params);
        p.model_gamma_inv = 1.0 / model_gamma;
        p.TABLE_reach_M = make_reach_m_table(p.reach_params, p.limit_J_max);

        p.sat = max(0.2, chroma_expand - (chroma_expand * chroma_expand_fact) * p.ts.log_peak);
        p.sat_thr = chroma_expand_thr / peakLuminance;
        p.compr = chroma_compress + (chroma_compress * chroma_compress_fact) * p.ts.log_peak;
        p.chroma_compress_scale = pow(0.03379 * peakLuminance, 0.30596) - 0.45135;

        p.mid_J = Y_to_J(p.ts.c_t * ref_luminance, p.input_params);
        p.focus_dist = focus_distance + focus_distance * focus_distance_scaling * p.ts.log_peak;
        double lower_hull_gamma = 1.14 + 0.07 * p.ts.log_peak;
        p.lower_hull_gamma_inv = 1.0 / lower_hull_gamma;
        p.TABLE_gamut_cusps = make_uniform_hue_gamut_table(p.reach_params, p.limit_params, p);
        for (int i = 0; i != totalTableSize; i = i + 1)
        {
            p.TABLE_hues[i] = p.TABLE_gamut_cusps[i][2];
        }
        p.TABLE_upper_hull_gamma = make_upper_hull_gamma_table(p.TABLE_gamut_cusps, p);
        p.hue_linearity_search_range = determine_hue_linearity_search_range(p.TABLE_hues);

        return p;
    }

    internal static double3 outputTransform_fwd(double3 aces,
        in ODTParams p)
    {
        double3 AP0_clamped = clamp_AP0_to_AP1(aces, 0.0, p.ts.forward_limit);

        double3 JMh = RGB_to_JMh(AP0_clamped, p.input_params);

        double3 tonemappedJMh = tonemap_and_compress_fwd(JMh, p);

        double3 compressedJMh = gamut_compress_fwd(tonemappedJMh, p);

        double3 RGBout = JMh_to_RGB(compressedJMh, p.limit_params);

        return RGBout;
    }

    internal static readonly Chromaticities AP0 = new Chromaticities {red=new double2(0.73470, 0.26530), green=new double2(0.00000, 1.00000), blue=new double2(0.00010, -0.07700), white=new double2(0.32168, 0.33767)};

    internal static readonly double3x3 AP0_XYZ_TO_RGB = XYZtoRGB_f33(AP0, 1.0);
    internal static readonly double3x3 AP0_RGB_TO_XYZ = RGBtoXYZ_f33(AP0, 1.0);

    internal static readonly Chromaticities AP1 = new Chromaticities {red=new double2(0.713, 0.293), green=new double2(0.165, 0.830), blue=new double2(0.128, 0.044), white=new double2(0.32168, 0.33767)};

    internal static readonly double3x3 AP1_XYZ_TO_RGB = XYZtoRGB_f33(AP1, 1.0);
    internal static readonly double3x3 AP1_RGB_TO_XYZ = RGBtoXYZ_f33(AP1, 1.0);

    internal static readonly double3x3 AP0_TO_AP1 = mult_f33_f33(AP0_RGB_TO_XYZ, AP1_XYZ_TO_RGB);
    internal static readonly double3x3 AP1_TO_AP0 = mult_f33_f33(AP1_RGB_TO_XYZ, AP0_XYZ_TO_RGB);

    internal static readonly Chromaticities REACH_PRI = AP1;

    internal static readonly int tableSize = 360;
    internal static readonly int additionalTableEntries = 2;
    internal static readonly int totalTableSize = tableSize + additionalTableEntries;
    internal static readonly int baseIndex = 1;

    internal static readonly double hue_limit = 360.0;

    internal static readonly int cuspCornerCount = 6;
    internal static readonly int totalCornerCount = cuspCornerCount + 2;
    internal static readonly int max_sorted_corners = 2 * cuspCornerCount;
    internal static readonly double reach_cusp_tolerance = 1e-3;
    internal static readonly double display_cusp_tolerance = 1e-7;

    internal static readonly double gamma_minimum = 0.0;
    internal static readonly double gamma_maximum = 5.0;
    internal static readonly double gamma_search_step = 0.4;
    internal static readonly double gamma_accuracy = 1e-5;

    internal static readonly double ref_luminance = 100.0;
    internal static readonly double L_A = 100.0;
    internal static readonly double Y_b = 20.0;
    internal static readonly double3 surround = new double3(0.9, 0.59, 0.9);

    internal static readonly double J_scale = 100.0;
    internal static readonly double cam_nl_Y_reference = 100.0;
    internal static readonly double cam_nl_offset = 0.2713 * cam_nl_Y_reference;
    internal static readonly double cam_nl_scale = 4.0 * cam_nl_Y_reference;

    internal static readonly double model_gamma = surround[1] * (1.48 + sqrt(Y_b / ref_luminance));

    internal static readonly double chroma_compress = 2.4;
    internal static readonly double chroma_compress_fact = 3.3;
    internal static readonly double chroma_expand = 1.3;
    internal static readonly double chroma_expand_fact = 0.69;
    internal static readonly double chroma_expand_thr = 0.5;

    internal static readonly double smooth_cusps = 0.12;
    internal static readonly double smooth_m = 0.27;
    internal static readonly double cusp_mid_blend = 1.3;

    internal static readonly double focus_gain_blend = 0.3;
    internal static readonly double focus_adjust_gain = 0.55;
    internal static readonly double focus_distance = 1.35;
    internal static readonly double focus_distance_scaling = 1.75;

    internal static readonly double compression_threshold = 0.75;

    internal static readonly double3x3 MATRIX_IDENTITY = new double3x3(new double3(1.0, 0, 0), new double3(0, 1.0, 0), new double3(0, 0, 1.0));

    internal static readonly int test_count = 5;

    internal static double testPositions(int i)
    {
        switch (i)
        {
            case 0: return 0.01;
            case 1: return 0.1;
            case 2: return 0.5;
            case 3: return 0.8;
            case 4: return 0.99;
            default: return 0.99;
        }
    }
}
}
