// SPDX-License-Identifier: Apache-2.0
// Copyright Contributors to the ACES Project.
// Generated by Tools/ACES2~/port-shader.cjs: the atlas sizes and the display constants. Aces2Atlas.cs builds the texels.
using Unity.Mathematics;
using UnityEngine;
namespace CustomToneMapping.Baker.ACES2
{
    internal static partial class Aces2Atlas
    {
        internal const int HueSamples=1440, Width=1441, Height=5, ConstantVectors=13;
        // The display constants, in the order Aces2.hlsl's Aces2Parameters() reads them.
        internal static void BuildConstants(in AcademyTransform.ODTParams p, Vector4[] constants, double aInMax)
        {
            Put(constants, 0, p.peakLuminance);
            Put(constants, 1, p.input_params.MATRIX_cone_response_to_Aab[0][0]);
            Put(constants, 2, p.input_params.MATRIX_cone_response_to_Aab[0][1]);
            Put(constants, 3, p.input_params.MATRIX_cone_response_to_Aab[0][2]);
            Put(constants, 4, p.input_params.MATRIX_cone_response_to_Aab[1][0]);
            Put(constants, 5, p.input_params.MATRIX_cone_response_to_Aab[1][1]);
            Put(constants, 6, p.input_params.MATRIX_cone_response_to_Aab[1][2]);
            Put(constants, 7, p.input_params.MATRIX_cone_response_to_Aab[2][0]);
            Put(constants, 8, p.input_params.MATRIX_cone_response_to_Aab[2][1]);
            Put(constants, 9, p.input_params.MATRIX_cone_response_to_Aab[2][2]);
            Put(constants, 10, p.limit_params.MATRIX_CAM16_c_to_RGB[0][0]);
            Put(constants, 11, p.limit_params.MATRIX_CAM16_c_to_RGB[0][1]);
            Put(constants, 12, p.limit_params.MATRIX_CAM16_c_to_RGB[0][2]);
            Put(constants, 13, p.limit_params.MATRIX_CAM16_c_to_RGB[1][0]);
            Put(constants, 14, p.limit_params.MATRIX_CAM16_c_to_RGB[1][1]);
            Put(constants, 15, p.limit_params.MATRIX_CAM16_c_to_RGB[1][2]);
            Put(constants, 16, p.limit_params.MATRIX_CAM16_c_to_RGB[2][0]);
            Put(constants, 17, p.limit_params.MATRIX_CAM16_c_to_RGB[2][1]);
            Put(constants, 18, p.limit_params.MATRIX_CAM16_c_to_RGB[2][2]);
            Put(constants, 19, p.limit_params.MATRIX_Aab_to_cone_response[0][0]);
            Put(constants, 20, p.limit_params.MATRIX_Aab_to_cone_response[0][1]);
            Put(constants, 21, p.limit_params.MATRIX_Aab_to_cone_response[0][2]);
            Put(constants, 22, p.limit_params.MATRIX_Aab_to_cone_response[1][0]);
            Put(constants, 23, p.limit_params.MATRIX_Aab_to_cone_response[1][1]);
            Put(constants, 24, p.limit_params.MATRIX_Aab_to_cone_response[1][2]);
            Put(constants, 25, p.limit_params.MATRIX_Aab_to_cone_response[2][0]);
            Put(constants, 26, p.limit_params.MATRIX_Aab_to_cone_response[2][1]);
            Put(constants, 27, p.limit_params.MATRIX_Aab_to_cone_response[2][2]);
            Put(constants, 28, p.limit_params.inv_cz);
            Put(constants, 29, p.ts.forward_limit);
            Put(constants, 30, p.limit_J_max);
            Put(constants, 31, p.model_gamma_inv);
            Put(constants, 32, p.sat);
            Put(constants, 33, p.sat_thr);
            Put(constants, 34, p.compr);
            Put(constants, 35, p.mid_J);
            Put(constants, 36, p.focus_dist);
            Put(constants, 37, p.lower_hull_gamma_inv);
            Put(constants, 38, 1.0/aInMax);
            Put(constants, 39, 1.0/p.limit_J_max);
            var ap1ToCam16=math.mul(p.input_params.MATRIX_RGB_to_CAM16_c,AcademyTransform.AP1_TO_AP0); // CTL AP1_TO_AP0 x RGB_to_CAM16
            Put(constants, 40, ap1ToCam16[0][0]);
            Put(constants, 41, ap1ToCam16[0][1]);
            Put(constants, 42, ap1ToCam16[0][2]);
            Put(constants, 43, ap1ToCam16[1][0]);
            Put(constants, 44, ap1ToCam16[1][1]);
            Put(constants, 45, ap1ToCam16[1][2]);
            Put(constants, 46, ap1ToCam16[2][0]);
            Put(constants, 47, ap1ToCam16[2][1]);
            Put(constants, 48, ap1ToCam16[2][2]);
        }
        static void Put(Vector4[] constants, int i, double x) => constants[i/4][i%4]=(float)x;
    }
}
